name: "Format Release Notes"
description: "Action to format the text of the release to the milestone"
inputs:
  repository:
    description: "owner/repository name"
    required: true
  milestone:
    description: "Milesone id, not title"
    required: true
  custom-row:
    description: "Custom format to row"
  custom-group-by-label:
    description: "Custom groups by label"
outputs:
  release-notes:
    description: "Formatted release notes"
runs:
  using: "node12"
  main: "index.js"
