name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
          
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: yarn

    - name: Install deps and build
      run: yarn install

    - name: Print token
      run: |
        echo "GH_TOKEN ${{ github.token }}"

    - name: Get formatted release notes
      id: get-release-notes
      uses: ./
      with:
        repository: ${{ github.repository }}
        milestone: 1
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Print release notes
      run: |
        echo "${{ steps.get-release-notes.outputs.release-notes }}"
